version: '3.5'
services:

  bot_app:
    image: php:8-apache
    volumes:
      - "./src:/var/www/html"
      - "./data:/var/www/data"
      - "./config:/var/www/config"
      - "./log:/var/www/log"
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8066:80"
      - "8443:443"